services:
  mongodb:
    container_name: mongodb
    networks:
      - cdp-network
    image: mongo:6.0.13
    volumes:
      - ./ssl:/etc/ssl:ro
    command: [
      "--tlsMode", "requireTLS",
      "--tlsCertificateKeyFile", "etc/ssl/mongodb.pem"
    ]
  service:
    build:
      context: ../..
    container_name: cdp-dotnet-backend-template
    image: cdp-dotnet-backend-template
    networks:
      - cdp-network
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_URLS: "http://+:8085"
      Mongo__DatabaseUri: "mongodb://mongodb:27017/?tls=true"
      TRUSTSTORE_MONGO: ${MONGODB_TEST_CA_PEM}

networks:
  cdp-network:
    driver: bridge

