name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: $${{ github.workflow }}
  cancel-in-progress: false
  queue: max

permissions:
  contents: read
  packages: read

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    if: github.run_number != 1
    name: CDP-build-workflow
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Build and Publish
        uses: DEFRA/cdp-build-action/build@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  ## SonarCloud
  ## Uncomment to enable SonarCloud scan
  ## Requires project to be set up in SonarCloud
  ## and the SonarCloud token to be set in the repository secrets
  # sonarcloud-scan:
  #   name: CDP SonarCloud Scan
  #   permissions:
  #     id-token: write
  #     pull-requests: write
  #     contents: read
  #     packages: read
  #   uses: ./.github/workflows/sonarcloud.yml
  #   needs: build
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
